name: Bump

on:
    push:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - master
            - next

jobs:
    bump:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm i -g semantic-release @semantic-release/changelog @semantic-release/github @semantic-release/git
            - run: cat .github/.releaserc.yml | envsubst > .releaserc.yml && semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
